Задание 1
Yurii-Bortsov/ProgrammingLanguages_2sem pull request #2
Opened 2023-04-04 10:51 UTC by Yurii-Bortsov

Пока что код без переопределения операторов ввода и вывода, но начало вот такое

2023-04-04 20:47 UTC, MarinaPaley requested changes
1. Нет документации
2. Вы не слушали ни одной моей лекции
3. Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
   - [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
   - [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
   - [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
   - [habr.com](https://habr.com/ru/post/328244/)
4. Подойдите к ~~Омельченко~~ автору кода и попросите полные комментарии к этому же коду &ndash; у него они уже больше недели.

2023-04-04 20:47 UTC, MarinaPaley commented on hexagon.cpp
> +std::vector <Point> hexagon_top;
[Вы ранее привлекались за хранение данных в глобальных переменных?](https://pikabu.ru/story/normalnyie_voprosyi_dlya_itsobesedovaniya_2351057)

2023-04-17 16:48 UTC, MarinaPaley requested changes
Все очень плохо. Подойдите лично!

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +        std::cerr << "Ошибка. Длина не может быть отрицательной.";
сначала проверка на валидность данных. если данные не валидны - выброс исключения,  а не сообщение  поток.

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +    this->lenght = lenght;
используйте инициализацию полей

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +Hexagon::Hexagon(Point centre, const double lenght)
центр планируете менять в методе?

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +        double y = round((lenght * sin(angle) + centre.y) * 10) / 10;
уберите логику в приватный метод. "Финт" с умножением и делением на 10 тоже необходимо объяснить.

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +
🔥 
Что это? 😢 
1. Ваш класс **не должен зависеть** от конкретной реализации потока ввода-вывода. Подробнее о связности и проблемах избыточной зависимости можно прочитать в [статье Германа Горелкина на Medium](https://medium.com/german-gorelkin/low-coupling-high-cohesion-d36369fb1be9).
Принципы [**SOLID**](http://sergeyteplyakov.blogspot.com/2014/10/solid.html), а именно [**D** – The Dependency Inversion Principle (DIP)](http://sergeyteplyakov.blogspot.com/2014/09/the-dependency-inversion-principle.html) также описывают проблемы связности. В частности можно привести цитату:
> Другими словами, DIP должен бороться с признаками плохого дизайном, которые так классно сформулировал все тот же Роберт Мартин в своей исходной статье о принципе инверсии зависимостей в 1996м:
> 1. Дизайн является жестким (rigid), если его тяжело изменить, поскольку любое изменение влияет на слишком большое количество других частей системы.
> 2. Дизайн является хрупким (fragile), если при внесении изменений неожиданно ломаются другие части системы.
> 3. Дизайн является неподвижным (immobile), если код тяжело использовать повторно в другом приложении, поскольку его слишком сложно «выпутать» из текущего приложения.

2. Сначала ввели из консоли, а потом показали пользователю?

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +const double Hexagon::Get_lenght()
Стили программирования
[CamelCase](https://ru.wikipedia.org/wiki/CamelCase)
[Snake case](https://ru.wikipedia.org/wiki/Snake_case)

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +    }
Ваша библиотека не должна зависеть от консоли или других потоков ввода-вывода!

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +double Hexagon::Area(const double lenght)
откуда на вход поступает длина? Кажется, что это принадлежность фигуры. 
Полное отсутствие ООП(

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +double Hexagon::Perimeter(const double lenght)
так же, что за длина вход?

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.cpp
> +double Hexagon::RadiusOfCircle(const double lenght)
так же

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.h
> +        Point centre = {0 , 0}; // координаты центра гексагона
зачем здесь какие-то присвоения?

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.h
> +        void PrintHexPoints();
метод должен выводить в строку что-то.

2023-04-17 16:48 UTC, MarinaPaley commented on hexagon.h
> +        const double Get_lenght();
стиль именования

2023-04-17 16:48 UTC, MarinaPaley commented on point.cpp
> +Point::Point(double valueX, double valueY)
Если параметры функции не изменяются, то они явно должны быть обозначены `const`
[By Alex Allain](https://www.cprogramming.com/tutorial/const_correctness.html)
>The const keyword allows you to specify whether or not a variable is modifiable. You can use const to prevent modifications to variables and const pointers and const references prevent changing the data pointed to (or referenced).
>Const дает вам возможность более четко документировать вашу программу и фактически обеспечивать соблюдение этой документации. Ключевое слово const обеспечивает вашим пользователям гарантии, позволяющие оптимизировать производительность без угрозы повреждения их данных, обеспечивая соблюдение вашей документации. Например, константные ссылки позволяют указать, что упомянутые данные не будут изменены; это означает, что вы можете использовать константные ссылки как простой и немедленный способ повышения производительности для любой функции, которая в настоящее время принимает объекты по значению, не беспокоясь о том, что ваша функция может изменить данные. Даже если это произойдет, компилятор предотвратит компиляцию кода и предупредит вас о проблеме. С другой стороны, если бы вы не использовали константные ссылки, у вас не было бы простого способа гарантировать, что ваши данные не были изменены.

2023-04-17 16:48 UTC, MarinaPaley commented on point.cpp
> +    this -> y = valueY;
Инициализация полей

2023-04-17 16:48 UTC, MarinaPaley commented on point.cpp
> +    return in;
```cpp
return in >> point.x >> point.y;
```

2023-04-17 16:48 UTC, MarinaPaley commented on point.h
> +        Point(double valueX, double valueY);
`const`

2023-04-18 15:57 UTC, MarinaPaley reviewed
Продолжайте. Разбейте метод, как обсудили, на три (`private`).

2023-04-18 15:57 UTC, MarinaPaley commented on hexagon.cpp
> +    for (int i = 0; i < 6; i++)
Лучше, если введете константу `количество_вершин = 6`

2023-04-18 15:57 UTC, MarinaPaley commented on hexagon.h
> +        std::vector<Point> hexagon_top; // список вершин гексагона
Не комментарии, а документация!

2023-04-18 15:57 UTC, MarinaPaley commented on hexagon.h
> +        double Area();
Если метод не изменяет объект, который он вызывает, его необходимо снабдить [модификатором `const`](https://docs.microsoft.com/en-us/cpp/cpp/const-cpp?view=msvc-170#const-member-functions)

2023-04-18 15:57 UTC, MarinaPaley commented on hexagon.h
> +        double Perimeter();
тоже `const`

2023-04-18 15:57 UTC, MarinaPaley commented on hexagon.h
> +        double RadiusOfCircle();
`const`

2023-04-19 10:08 UTC, MarinaPaley requested changes

2023-04-19 10:08 UTC, MarinaPaley commented on hexagon.cpp
> +    for (int i = 0; i < 6; i++)
Да, а использовать константу?

2023-04-19 10:08 UTC, MarinaPaley commented on hexagon.h
> +        const void Math();
в `private`

2023-04-19 10:08 UTC, MarinaPaley commented on hexagon.h
> +         */
`const` в конце.
Если метод не изменяет объект, который он вызывает, его необходимо снабдить [модификатором `const`](https://docs.microsoft.com/en-us/cpp/cpp/const-cpp?view=msvc-170#const-member-functions)

2023-04-19 16:58 UTC, MarinaPaley reviewed
Исправьте немного. Это не ошибка, просто зачем лишние переменные. Приступайте к тестам.

2023-04-19 16:58 UTC, MarinaPaley commented on hexagon.cpp
> +    return angle;
`return ((90 + 60 * i) * M_PI) / 180;`

2023-04-19 16:58 UTC, MarinaPaley commented on hexagon.cpp
> +    return x;
`return lenght * cos(angle) + centre.x;`

2023-04-19 16:58 UTC, MarinaPaley commented on hexagon.cpp
> +    return y;
`return lenght * sin(angle) + centre.y;`

2023-04-19 17:14 UTC, Yurii-Bortsov commented
Хорошо, спасибо, хотел посоветоваться, какие тесты лучше использовать на mac os? Работаю в visual studio code.

2023-04-20 06:03 UTC, MarinaPaley commented
@Yurii-Bortsov [Google Tests](https://alexanderbussan.medium.com/getting-started-with-google-test-on-os-x-a07eee7ae6dc), [вот тут статья](https://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle)

2023-05-02 12:05 UTC, MarinaPaley requested changes

2023-05-02 12:05 UTC, MarinaPaley commented on point.h
> +        bool operator == (const Point& point);
еще `!=`

2023-05-02 13:01 UTC, merged